### PR TITLE
Add Maggie Dreyer's public key to authorized keys.

### PR DESCRIPTION
**Pull request by Magisus**

### CODE REVIEW

**Comment by BillWeiss** [comment]
Embarrassingly, this is super stale. @Magisus , do you still need access to these boxes? If so, can you merge your branch?

**Comment by Magisus** [comment]
I haven't needed it yet, so I guess not. Getting my key in here was part of some onboarding doc, but it hasn't been relevant. What exactly would this give me access to?

**Comment by BillWeiss** [comment]
(shrug)
I'm a fan of closing this out, and then you can reopen if you need it some time. Fair?

**Comment by Magisus** [comment]
Sounds good.

**Pull request closed without merging**
