### PR TITLE
Add rob.lucke to Puppet SSH keys

### PR DESCRIPTION
**Pull request by RobLuckePuppet**
Please add my information to the key store.  This was missed during my on-boarding process.

### CODE REVIEW

**Comment by ericwilliamson** [comment]
@RobLuckePuppet You also need to add it here: https://github.com/puppetlabs/puppetlabs-sshkeys/blob/master/templates/ssh/authorized_keys

**Comment by RobLuckePuppet** [comment]
Thank you, I was already in the blob, just not here for some reason.

**Comment by ericwilliamson** [comment]
@RobLuckePuppet I don't see your key in that blob, is it under a different name & key?

**Comment by RobLuckePuppet** [comment]
I'm taking Doug Rosser's word for the blob entry.  It should be the same name and key.

**Comment by RobLuckePuppet** [comment]
Just checked.  It's there.  Line 1324.

**Comment by RobLuckePuppet** [comment]
https://github.com/puppetlabs/puppetlabs-modules/blob/production/site/virtual/manifests/users.pp

**Comment by RobLuckePuppet** [comment]
Well, this would probably explain a few wierdities that I've seen over the last year.

**Comment by ericwilliamson** [comment]
> https://github.com/puppetlabs/puppetlabs-modules/blob/production/site/virtual/manifests/users.pp

Thats a different repository.

This repo is what beaker uses to allow you access to SUT's that had the `--root-keys` flag passed to beaker. 

To my knowledge, having your key as a single `.pub` file don't do much. You need to add it to that `authorized_files` file.

https://github.com/puppetlabs/beaker/blob/master/lib/beaker/host_prebuilt_steps.rb#L29

which calls 

https://github.com/puppetlabs/puppetlabs-sshkeys/blob/master/templates/scripts/manage_root_authorized_keys#L6

**Pull request closed without merging**
